### ISSUE TITLE
Reviewed by WALRUS

### ISSUE THREAD

**Issue by djung30** [agurovich20/03Consonants#1]
Things to work on: 
Use of the timing method may be hindered by noise from the computer, maybe consider adding a second way to compare? (ex. # of times the program accesses the array) 

Math.random should be multiplied by _hi-_lo+1 not _hi

Consider adding support for reading input from and pushing output to external files

Need to reconsider the functionality of System.countMilliSeconds() in the main method (subtract the values)

**Comment by Ozb888** [comment]
can u elaborate on what u mean by noise from the computer?

**Comment by Ozb888** [comment]
.
